/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.datos;

import controlador.generarDatos.generarPersona;
import controlador.json.JsonController;
import controlador.tda.lista.ListaEnlazadaServices;
import controlador.utiles.TipoOrdenacion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdk.nashorn.internal.parser.JSONParser;
import modelo.persona.Persona;
import vista.datos.tabla.TablaPersonas;

/**
 *
 * @author kali
 */
public class FrmDatos extends javax.swing.JFrame {
    
    private TablaPersonas ta = new TablaPersonas();
    ListaEnlazadaServices<Persona> list = new ListaEnlazadaServices<>();
    
    /**
     * Creates new form FrmDatos
     */
    public FrmDatos() {
        initComponents();
    }

    private void cargarTabla(ListaEnlazadaServices<Persona> lista ) throws IOException {
        //ListaEnlazadaServices<Persona> lista = new JsonController().leer("Personas.json");
        ta.setLista(lista);
        tbl_tabla.setModel(ta);
        tbl_tabla.updateUI();
    }
    
    private void cargarTabla() throws IOException {
        ta.setLista(list);
        tbl_tabla.setModel(ta);
        tbl_tabla.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTADO DE DATOS"));
        jPanel3.setLayout(null);

        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tabla);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 460, 130);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Métodos de ordenación"));
        jPanel2.setLayout(null);

        btn_cancelar.setText("Quickshort");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancelar);
        btn_cancelar.setBounds(160, 30, 110, 25);

        btn_guardar.setText("Shell");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_guardar);
        btn_guardar.setBounds(20, 30, 110, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try {
            // TODO add your handling code here:
            
            //cargarTabla(new generarPersona().generarLista(list, 10000));
            try {
                list.setLista(list.getLista().ordenar_seleccion("nombre", TipoOrdenacion.ASCENDENTE));
            } catch (Exception ex) {
                Logger.getLogger(FrmDatos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            cargarTabla();
            
            
        } catch (IOException ex) {
            Logger.getLogger(FrmDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        try {
                list.setLista(list.getLista().ordenar_seleccion("nombre", TipoOrdenacion.ASCENDENTE));
                cargarTabla();
            } catch (Exception ex) {
                Logger.getLogger(FrmDatos.class.getName()).log(Level.SEVERE, null, ex);
            }   
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                FrmDatos dialog = new FrmDatos();
                dialog.setVisible(true);
                dialog.list = new generarPersona().generarLista(dialog.list, 10000);
                //new JsonController().guardar(dialog.list, "Personas.json");
                dialog.cargarTabla();
            } catch (IOException ex) {
                Logger.getLogger(FrmDatos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tabla;
    // End of variables declaration//GEN-END:variables
}
